# Generated by Django 4.2.7 on 2023-12-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_equipment_remove_car_equipment_car_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='translation',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
